### ISSUE TITLE
v3

### ISSUE THREAD

**Issue by evgenyrodionov** [evgenyrodionov/redux-logger#174]
And here we go.
I was very busy last months, but now I can continue development.
### Roadmap
- [ ] correct logging in node (ssr, f.e.)
- [ ] correct logging in react-native
- [ ] better docs, because now it's little bit messy

anything else?

**Comment by evgenyrodionov** [comment]
#158 too

**Comment by BirdLeeSCUT** [comment]
When I update to 2.7.0, diff is still not appear ? Is it ready?

**Comment by grushetsky** [comment]
Diff is turned off by default. It doesn't work really well, actually (currently handling simple diff cases only).

In order to use the feature you should set `diff` property to `true` in your options object.

**Comment by evgenyrodionov** [comment]
Abandoned
