### ISSUE TITLE
Redux Logger 4.x 

### ISSUE THREAD

**Issue by grushetsky** [evgenyrodionov/redux-logger#292]
Redux Logger has been staling for some time and we're kind of upset about leaving it behind. Yet it keeps logging those Redux actions for us on a daily basis. ✌️ So, we decided to bring back some of our attention to the project and would like to outline the goals for the next major version. But it wouldn't be fair to do it without you, dear community. Your feedback and suggestions are warmly welcomed! 🙏

## Overview

Now, the logging task itself is quite straightforward and yet you can't state the same about our code base. 😏 It is really messy. It complicates adding new features and fixing bugs. So, one of the first goals for the next version is to get rid of legacy code by embracing testing first approach along with static typing (Jest and TypeScript are going to help us with that).

As a result of refactoring, we expect to reduce the number of options for `createLogger` and most probably to see some changes to current API.

We also consider to bring in a requested feature which is the ability of intervention into logging process. Redux Logger might accept an _interceptor_ function that is called right before outputting the log message. An interceptor is a way to execute custom logic before logging (e.g., modify the log message, forward the message to another kind of console, abort logging, etc.)

## General Plan

There are a couple of milestones on the road to 4.0:

1. Enhance the tooling (Jest, TypeScript, Yarn, etc.)

2. Introduce interceptor API and use it for some of the current features.

3. Add contribution guide.

4. Add example project, fix bugs, add features.

## Major Tasks

Here is the initial list of tasks which is going to be modified along the way:

- [ ] Resolve log entries ordering bug.
- [ ] Add Redux 4.x support.
- [ ] Switch to TypeScript and TSLint.
- [ ] Add example app with live settings tweaking.
- [ ] Add contribution guide.
- [ ] Add interceptor API. Just an example to imagine it:

```javascript
const reduxLogger = createLogger({
  logger: fancyConsole,
  interceptor: ({ action, previousState, nextState, logger }) => ({
    logger.group(`Anything you wish: ${action.type}`);
    logger.log(previousState, nextState);
    logger.log('Bye, bye!');
    logger.doSomethingElse(action);
  });
});
```

- [ ] Reduce API complexity:
  - [ ] Simplify message formatting approach (currently colouring, title formatting and entry collapsing are separate options).
  - [ ] Deprecate options like `predicate` in favour of interceptor API.
  - [ ] Drop support for currently deprecated options.
- [ ] Enhanced console output by default. Yes, you can style console messages in modern browsers:

```javascript
console.log("%c➡️ Custom text formatting", "color: white; font-size: xx-large; background-color: gray; background-image: url(\"https://img.etsystatic.com/il/d79007/1098750874/il_570xN.1098750874_hama.jpg\"); font-family: Tahoma; margin-left: 15%; padding: 0 20%; line-height: 2; text-shadow: black 3px 0 10px; text-decoration: underline dotted red;");
```

![Example](https://s13.postimg.org/cpbif7fvb/Customized_Log_Entry.png)

- [ ] Switch to Jest.
- [ ] Add official TypeScript type definitions.

Each entry in the list above will be assigned a specific issue.

Features and tasks to consider:

- Use Prettier for code formatting?
- Add stable state diffing option?
- Settle the list of supported browsers?
- Create a cross-browser logger that outputs to a custom console (app overlay, separate browser extension)?
- Guide for usage with React Native?

## Contribution

Redux Logger is a tiny library, but we definitely need your helping hand. Please, share your experience and join us in shaping the roadmap. You can add suggestions to the current issue. Thank you for help!

**Comment by grushetsky** [comment]
Meanwhile, you can follow the progress in the [_next_](https://github.com/evgenyrodionov/redux-logger/tree/next) branch.

**Comment by thiamsantos** [comment]
[microbundle](https://github.com/developit/microbundle) could be used to bundle the library.

**Comment by MichelSimonot** [comment]
I really like the idea of an interceptor (and it would solve all my problems). I'm getting different vibes from these two lines, though:

> An interceptor is a way to execute custom logic before logging

> 2. Introduce interceptor API and use it for some of the current features.

The first says that it would just be another step in the logging process.
The second implies that it could _wrap_ some current features [of the process].

-----
I think an interceptor would work really well to simplify the "core" library. I'm a big proponent of "separation of concerns" and simplicity, so there's an opportunity I can see here. As you said, the logging task itself is quite straightforward.

Maybe an interceptor-like idea (I see it more like a "log handler" at the end of the process) could move the responsibility for the "transformations and extra things" out of the core library, to be more like utilities/helpers (used by the default or provided interceptors).

**Comment by hg-pyun** [comment]
I would like to add the ability to turn off log for specific actions. For example, using the redux-logger in the case of input onChange has the problem of seeing too many consoles. How about this?

**Comment by hg-pyun** [comment]
@MichelSimonot Thanks. I will read it.

**Comment by Rycochet** [comment]
One thing I've just hit with performance is in the `diff` option - it's easy enough to filter what's getting changed, but my Store is immutable (Typescript `readonly` style rather than `Object.setProperty` style). Quite often I'm changing a single string or number at the root of the Store, but it still has to examine the entire Store.

If it had an `immutable: boolean` option that told diff not to both checking a property (and its children) if it's pointing at the same object it would make things more performant for logging, while still keeping the useful diff output itself (I basically do that for seeing if I need to fire the change action).

**Comment by MichelSimonot** [comment]
I played around a bit to see what my above idea would look like: https://gist.github.com/MichelSimonot/b59b4f5445a5ad3cd90c8a1c498b51e7

I essentially took tswaters' suggestion for fixing the log entry bug ([from here](https://github.com/evgenyrodionov/redux-logger/pull/276#issuecomment-354988939)) and used the interceptor concept to separate out the actual logging and extra things. Its pretty simple and works well.

The other part to figure out is how to make it easy for the interceptor to do all of the extra things. I think it'd be done similarly to how I showed using the `styles`, as stand-alone utilities. That way an application can import / make use of them however they see fit (or use their own) for their own logging use case.

Thoughts?

**Comment by MichelSimonot** [comment]
@grushetsky If I make a PR to the _[next](https://github.com/evgenyrodionov/redux-logger/tree/next)_ branch (re: interceptor, reduce complexity; see above comment), can I expect someone to take a look at it? I would very much like to help out.

**Comment by eranimo** [comment]
@MichelSimonot Hi—we plan on taking a close look at your branch as part of the next version. For context, I work for LogRocket and we are the new maintainers of this package. I like the direction you took, and we have the same goals in mind for 4.0.
